services:
  cookie-crafter-backend:
    image: ghcr.io/albina0104/cookie-crafter-backend:latest
    networks:
      - cookie-crafter-network
    volumes:
      - /home/albina/logs:/app/logs

  cookie-crafter-frontend:
    image: ghcr.io/albina0104/cookie-crafter-frontend:latest
    networks:
      - cookie-crafter-network

  my-apache:
    image: ghcr.io/albina0104/my-apache:latest
    ports:
      - '80:80'
      - '443:443'
    networks:
      - cookie-crafter-network
    volumes:
      - /etc/letsencrypt/live/cookie-crafter.com:/usr/local/apache2/ssl-certs
      - /etc/letsencrypt/archive/cookie-crafter.com:/usr/local/archive/cookie-crafter.com
      - /home/albina/logs:/usr/local/apache2/logs

networks:
  cookie-crafter-network:
    name: cookie-crafter-network
    driver: bridge
