name: Deploy Cookie Crafter project

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  deploy-all:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_DOMAIN }} >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo "echo $SSH_PASSPHRASE" > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - > /dev/null

      - name: Upload docker-compose file to server
        run: scp docker-compose.yml ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_DOMAIN }}:/home/${{ secrets.SERVER_USERNAME }}/cookie-crafter/

      - name: Deploy
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_DOMAIN }} << 'EOF'
            echo "${{ secrets.GHCR_ACCESS_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
            cd /home/${{ secrets.SERVER_USERNAME }}/cookie-crafter
            docker compose down
            docker rmi $(docker images -a -q)
            docker compose up -d
          EOF
